# Generated by Django 5.2.3 on 2025-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
